word_list = [
    "aardvark", "airplane", "alligator", "alphabet", "algorithm",
    "baboon", "backpack", "balloon", "banana", "baseball",
    "battery", "beach", "bicycle", "blanket", "butterfly",
    "camel", "camera", "campfire", "canyon", "captain",
    "carrot", "castle", "chocolate", "computer", "crocodile",
    "diamond", "dinosaur", "dolphin", "dragon", "drumstick",
    "eagle", "earthquake", "elephant", "engineer", "envelope",
    "factory", "falcon", "feather", "fireplace", "forest",
    "function", "galaxy", "garden", "giraffe", "glacier",
    "guitar", "hamburger", "hangman", "harbour", "helicopter",
    "hospital", "iceberg", "iguana", "internet", "island",
    "jacket", "jaguar", "jellyfish", "journey", "jungle",
    "kangaroo", "keyboard", "kitchen", "koala", "ladder",
    "lantern", "library", "lightning", "lighthouse", "lobster",
    "machine", "magnet", "marathon", "microscope", "mountain",
    "narwhal", "necklace", "network", "notebook", "octopus",
    "orchard", "ostrich", "oxygen", "pancake", "penguin",
    "piano", "pineapple", "pirate", "planet", "pyramid",
    "queen", "quicksand", "rabbit", "rainbow", "rocket",
    "sandwich", "satellite", "scorpion", "software", "spaceship",
    "sunflower", "telephone", "telescope", "thunderstorm",
    "tiger", "triangle", "umbrella", "university", "vacation",
    "variable", "vegetable", "volcano", "walrus", "waterfall",
    "website", "whistle", "xylophone", "yoghurt", "zeppelin",
    "zebra", "zookeeper"
]